"""Add recurrence to Booking model

Revision ID: d6ccfdbb06a8
Revises: b873a03388e5
Create Date: 2024-07-10 17:12:47.552629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6ccfdbb06a8'
down_revision = 'b873a03388e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurrence', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('recurrence')

    # ### end Alembic commands ###
